[build-system]
requires = ["maturin>=1.6,<2"]
build-backend = "maturin"

[project]
name = "tsarcore_native"
version = "0.2.4"
requires-python = ">=3.8"
description = "Native acceleration for TsarChain (pyo3)"
authors = [{ name = "Tsar Studio" }]
license = { file = "LICENSE" }
readme = "README.md"
classifiers = [
  "Programming Language :: Rust",
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
]
